package org.continuouspath.justtype

/**
 * British/American preference for English word ranking. Mirrors [SpanishRegion]: the pooled English
 * word DB contains BOTH spellings of every pair (colour/color, centre/center, realise/realize) plus
 * region-specific vocabulary (lorry, torch, apartment). When the user picks a region, the
 * dispreferred form is SOFT-DEMOTED in the ambiguous selection list — sunk toward the end, never
 * removed, so a user quoting the other variety can still reach it.
 *
 * Both spellings must stay present whichever region is chosen, which is why this is a ranking skew
 * rather than two separate databases: a UK user reading American text still needs "color", and the
 * pair rarely competes anyway (colour is six keystrokes, color five).
 *
 * The per-word tags come from `EnglishRegionTags.txt`, generated by
 * `tools/case-seeds/parse_wiktionary_regions.py --labels en`, and are baked into the DB's
 * classMask at build time.
 */
object EnglishRegion {
	const val ANY = "any" // no preference (default; pooled behaviour)
	const val UK = "en-GB"
	const val US = "en-US"

	/**
	 * True if [classMask] marks [word]'s spelling as belonging to the other variety. Caller gates
	 * this to English being the active typing language.
	 */
	fun demote(classMask: Long, region: String): Boolean = when (region) {
		UK -> (classMask and ClassMasks.CLASS_REGION_US_SKEW_MASK) != 0L
		US -> (classMask and ClassMasks.CLASS_REGION_GB_SKEW_MASK) != 0L
		else -> false
	}
}
